#pragma once



// Backlight control
#define TWODOTFOUR_LCD_PIN_BACKLIGHT GPIO_NUM_21  // Matches backlight = Pin(21)


// === Display (ILI9341 / ILI9486) ===
#define TWODOTFOUR_LCD_SPI_HOST SPI2_HOST  // SPI2 = VSPI = SPI(1) in MicroPython

#define TWODOTFOUR_LCD_HORIZONTAL_RESOLUTION 240
#define TWODOTFOUR_LCD_VERTICAL_RESOLUTION 320

#define TWODOTFOUR_LCD_DRAW_BUFFER_HEIGHT (TWODOTFOUR_LCD_VERTICAL_RESOLUTION / 10)
#define TWODOTFOUR_LCD_DRAW_BUFFER_SIZE (TWODOTFOUR_LCD_HORIZONTAL_RESOLUTION * TWODOTFOUR_LCD_DRAW_BUFFER_HEIGHT)

// Match these to: dc=2, cs=15, rst=0
#define TWODOTFOUR_LCD_PIN_DC  GPIO_NUM_2
#define TWODOTFOUR_LCD_PIN_CS  GPIO_NUM_15
#define TWODOTFOUR_LCD_PIN_RST GPIO_NUM_0

#define TWODOTFOUR_TOUCH_PIN_CS GPIO_NUM_33
